#!/bin/bash

# ============================================================================
# Step 5: Apply database migrations
# ============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/common.sh"

PROJECT_ROOT="$(get_project_root)"
MIGRATIONS_DIR="$PROJECT_ROOT/supabase/migrations"

get_migrations() {
    (
        cd "$MIGRATIONS_DIR" || exit 1
        ls -1 *.sql 2>/dev/null | sort
    )
}

validate_migrations() {
    log_info "Validating migration files..."

    mapfile -t MIGRATIONS < <(get_migrations)

    if [[ ${#MIGRATIONS[@]} -eq 0 ]]; then
        log_error "No migration files found in $MIGRATIONS_DIR"
        return 1
    fi

    log_success "Found ${#MIGRATIONS[@]} migration files"
    return 0
}

generate_combined_sql() {
    log_step "Generating combined SQL file..."

    local output_file="$PROJECT_ROOT/supabase/combined_setup.sql"

    cat > "$output_file" << 'EOF'
-- ============================================================================
-- Supabase Complete Setup
-- ============================================================================
-- Generated by setup scripts
--
-- Instructions:
-- 1. Open Supabase Dashboard > SQL Editor
-- 2. Copy and paste this entire file
-- 3. Click "Run" to execute
--
-- This script is idempotent - safe to run multiple times
-- ============================================================================

EOF

    for migration in "${MIGRATIONS[@]}"; do
        local migration_path="$MIGRATIONS_DIR/$migration"
        echo "" >> "$output_file"
        echo "-- ========================================" >> "$output_file"
        echo "-- Migration: $migration" >> "$output_file"
        echo "-- ========================================" >> "$output_file"
        echo "" >> "$output_file"
        cat "$migration_path" >> "$output_file"
        echo "" >> "$output_file"
    done

    log_success "Generated: $output_file"
    echo ""
    echo "To apply manually:"
    echo "  1. Open: https://supabase.com/dashboard/project/YOUR_PROJECT/sql"
    echo "  2. Paste contents of: supabase/combined_setup.sql"
    echo "  3. Click 'Run'"

    return 0
}

apply_migrations() {
    local mode="${1:-auto}"  # auto, manual, cli

    log_step "Applying database migrations..."

    # Load environment
    load_env "$PROJECT_ROOT"

    # Validate migrations exist
    validate_migrations || return 1

    local project_ref="${SUPABASE_PROJECT_REF:-$(get_supabase_project_ref)}"

    if [[ "$mode" == "manual" ]]; then
        generate_combined_sql
        return 0
    fi

    # Check for Supabase CLI
    if command_exists supabase; then
        log_info "Using Supabase CLI..."

        cd "$PROJECT_ROOT"

        # Link project if not already linked
        if [[ ! -f "$PROJECT_ROOT/supabase/.temp/project-ref" ]]; then
            supabase link --project-ref "$project_ref" 2>/dev/null || true
        fi

        # Push migrations
        if supabase db push 2>/dev/null; then
            log_success "Migrations applied via CLI"
        else
            log_warning "CLI push failed, migrations may already exist"
        fi
    else
        log_warning "Supabase CLI not installed"
        echo ""
        echo "Options:"
        echo "  1. Install CLI: brew install supabase/tap/supabase"
        echo "  2. Use manual mode: yarn setup:db:manual"
        echo ""

        read -p "  Generate combined SQL for manual execution? [Y/n] " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Nn]$ ]]; then
            generate_combined_sql

            echo ""
            read -p "  Open SQL Editor in browser? [Y/n] " -n 1 -r
            echo
            if [[ ! $REPLY =~ ^[Nn]$ ]]; then
                open_url "https://supabase.com/dashboard/project/$project_ref/sql/new"
            fi
        fi
    fi

    return 0
}

show_verification_checklist() {
    log_step "Verification checklist..."

    local project_ref="${SUPABASE_PROJECT_REF:-$(get_supabase_project_ref)}"

    echo ""
    echo "Please verify in Supabase Dashboard:"
    echo "https://supabase.com/dashboard/project/$project_ref"
    echo ""
    echo "Tables (Database > Tables):"
    echo "  [ ] profiles"
    echo "  [ ] subscriptions"
    echo "  [ ] products"
    echo "  [ ] prices"
    echo "  [ ] credit_transactions"
    echo "  [ ] processing_jobs"
    echo ""
    echo "RPC Functions (Database > Functions):"
    echo "  [ ] increment_credits"
    echo "  [ ] decrement_credits"
    echo "  [ ] has_sufficient_credits"
    echo "  [ ] get_active_subscription"
    echo ""
    echo "RLS (each table should show 'RLS Enabled'):"
    echo "  [ ] All tables have RLS enabled"
    echo ""
}

# Run if executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    mode="${1:-auto}"
    apply_migrations "$mode"
    show_verification_checklist
fi
