/**
 * Article Types for AI Content Generation Engine
 *
 * Defines interfaces for articles, generation input/output, and related structures.
 */

import type { IGscArticleContext } from './opportunity.types';

/**
 * Article status enum representing the lifecycle of an article
 */
export type ArticleStatus =
  | 'planned'
  | 'queued'
  | 'generating'
  | 'draft'
  | 'qa_checking'
  | 'qa_failed'
  | 'qa_passed'
  | 'approved'
  | 'rejected'
  | 'reviewed'
  | 'published'
  | 'failed'
  | 'failed_quality'
  | 'failed_timeout';

/**
 * Full article interface matching the database schema
 */
export interface IArticle {
  id: string;
  campaign_id: string | null;
  user_id: string;
  project_id: string | null;
  title: string | null;
  content: string | null;
  primary_keyword: string;
  status: ArticleStatus;
  ai_model_used: string | null;
  seo_score: number | null;
  ai_detection_score: number | null;
  word_count: number | null;
  meta_description: string | null;
  published_url: string | null;
  slug: string | null;
  credits_used: number;
  generation_error: string | null;
  rejection_reason: string | null;
  outline: IArticleOutline | null;
  token_count: number | null;
  generation_time_ms: number | null;
  generated_at: string | null;
  published_at: string | null;
  scheduled_publish_at: string | null;
  created_at: string;
  updated_at: string;
  // Image generation fields
  image_preset: string | null;
  image_count: number;
  // Stale recovery fields
  last_attempt_at: string | null;
  attempt_count: number;
  // Semantic deduplication fields (E10)
  topic_fingerprint: number[] | null;
  similarity_score: number | null;
  similar_to_article_id: string | null;
  // QA pipeline fields (E11)
  qa_results: IQAResult | null;
  // AI Detection fields
  ai_detection_details: IAIDetectionDetails | null;
  ai_detection_provider: 'heuristic' | 'originality' | null;
}

/**
 * Structured outline generated by the LLM in the first step of generation
 */
export interface IArticleOutline {
  title: string;
  metaDescription: string;
  slug: string;
  sections: Array<{
    heading: string;
    subheadings?: string[];
    keyPoints: string[];
  }>;
}

/**
 * Input for article generation API
 */
export interface IGenerateArticleInput {
  /** The primary keyword or topic for the article */
  keyword: string;
  /** ID of the project this article belongs to */
  projectId: string;
  /** ID of the campaign this article belongs to (REQUIRED) */
  campaignId: string;
  /** OpenRouter model ID (defaults to config if not specified) */
  model?: string;
  /** Writing tone: professional, casual, witty, academic */
  tone?: 'professional' | 'casual' | 'witty' | 'academic';
  /** Target word count (800-3000, default 1500) */
  targetWordCount?: number;
  /** Image generation preset key (optional, no images if not specified) */
  imagePreset?: string;
  /** Force regeneration even if an article with the same keyword exists */
  forceRegenerate?: boolean;
  /** Skip semantic deduplication check (for admin/advanced users) */
  skipSemanticDedup?: boolean;
  /** GSC context for GSC-aware article generation (optional) */
  gscContext?: IGscArticleContext;
  /** Enable YouTube video embedding enrichment */
  enableYoutube?: boolean;
  /** Enable citation enrichment with fact verification (+1 credit) */
  enableCitations?: boolean;
  /** Enable internal linking to related articles in the same project */
  enableInternalLinks?: boolean;
}

/**
 * Response from article generation API (202 Accepted)
 */
export interface IGenerateArticleResponse {
  articleId: string;
  status: 'generating';
}

/**
 * Response from article details API (with images and campaign)
 */
export interface IArticleDetailResponse {
  article: IArticle & {
    campaigns?: {
      id: string;
      name: string;
    } | null;
    article_images?: Array<{
      id: string;
      position: number;
      image_url: string | null;
      prompt: string;
      status: string;
    }>;
  };
}

/**
 * Response from article details API (legacy)
 */
export interface IArticleResponse {
  article: IArticle;
}

/**
 * Article with campaign info (for list views)
 */
export interface IArticleWithCampaign extends IArticle {
  /** Campaign info (joined) */
  campaigns: {
    id: string;
    name: string;
  } | null;
  /** Article images (joined, for thumbnails in list; prompt included in detail) */
  article_images?: Array<{
    id: string;
    position: number;
    image_url: string | null;
    prompt?: string;
    status: string;
  }>;
  /** Latest delivery records (joined) */
  integration_deliveries?: Array<{
    id: string;
    status: string;
    external_url: string | null;
    delivered_at: string | null;
  }>;
}

/**
 * Response from articles listing API
 */
export interface IArticlesListResponse {
  articles: IArticleWithCampaign[];
  total: number;
}

/**
 * Query parameters for articles listing
 */
export interface IArticlesListParams {
  projectId?: string;
  status?: ArticleStatus;
  limit?: number;
  offset?: number;
}

/**
 * Article image record from database
 */
export interface IArticleImage {
  id: string;
  article_id: string;
  position: number;
  image_url: string | null;
  prompt: string;
  section_context: string | null;
  replicate_model: string;
  preset_key: string;
  status: 'pending' | 'generating' | 'completed' | 'failed';
  error: string | null;
  replicate_prediction_id: string | null;
  generation_time_ms: number | null;
  created_at: string;
}

/**
 * Image marker parsed from article markdown
 */
export interface IImageMarker {
  position: number;
  sectionContext: string;
}

/**
 * Result from generating a single image
 */
export interface IImageResult {
  position: number;
  imageUrl: string | null;
  prompt: string;
  model: string;
  presetKey: string;
  status: 'completed' | 'failed';
  error?: string;
  generationTimeMs?: number;
  replicatePredictionId?: string;
}

/**
 * QA check result stored with article
 */
export interface IQAResult {
  /** Overall pass/fail status */
  passed: boolean;
  /** Reason for overall failure */
  failureReason?: string;
  /** Timestamp of check */
  checkedAt: string;
  /** Individual check results (nested under results to match IQACheckResult storage format) */
  results: {
    plagiarism: {
      passed: boolean;
      similarityScore: number;
      flaggedPhrases: number | { phrase: string; start: number; end: number }[];
    };
    factConsistency: {
      passed: boolean;
      score: number;
      inconsistencyCount: number;
    };
    readability: {
      passed: boolean;
      fleschKincaidGrade: number;
      fleschReadingEase: number;
    };
    aiLikelihood: {
      passed: boolean;
      aiScore: number;
      confidence: 'low' | 'medium' | 'high';
      detectedPatterns?: string[];
    };
  };
}

/**
 * Similar article information for near-duplicate detection
 */
export interface ISimilarArticle {
  articleId: string;
  title: string | null;
  similarity: number;
  similarityPercent: number;
  status?: ArticleStatus;
  primaryKeyword?: string;
}

/**
 * Response from similarity check API
 */
export interface ISimilarityCheckResponse {
  /** Whether similar articles were found */
  isSimilar: boolean;
  /** Highest similarity score (0-1) */
  maxSimilarity: number;
  /** Highest similarity as percentage */
  maxSimilarityPercent: number;
  /** ID of the most similar article */
  similarArticleId?: string;
  /** List of similar articles with details */
  similarArticles: ISimilarArticle[];
  /** Human-readable message */
  message: string;
}

/**
 * Similarity check request parameters
 */
export interface ISimilarityCheckRequest {
  topic: string;
  projectId: string;
  threshold?: number;
  maxResults?: number;
  excludeArticleId?: string;
}

/**
 * AI Detection details stored with article
 */
export interface IAIDetectionDetails {
  /** Provider that produced the score */
  provider: 'heuristic' | 'originality';
  /** Confidence level of the detection */
  confidence: 'low' | 'medium' | 'high';
  /** Detected AI patterns (from heuristic analysis) */
  detectedPatterns: string[];
  /** When the analysis was performed */
  analyzedAt: string;
  /** Original provider score (0-1 for heuristic, 0-100 for Originality.ai) */
  rawScore?: number;
}
