/**
 * Article Types for AI Content Generation Engine
 *
 * Defines interfaces for articles, generation input/output, and related structures.
 */

/**
 * Article status enum representing the lifecycle of an article
 */
export type ArticleStatus = 'queued' | 'generating' | 'draft' | 'reviewed' | 'published' | 'failed';

/**
 * Full article interface matching the database schema
 */
export interface IArticle {
  id: string;
  campaign_id: string | null;
  user_id: string;
  project_id: string | null;
  title: string | null;
  content: string | null;
  primary_keyword: string;
  status: ArticleStatus;
  ai_model_used: string | null;
  seo_score: number | null;
  ai_detection_score: number | null;
  word_count: number | null;
  meta_description: string | null;
  published_url: string | null;
  slug: string | null;
  credits_used: number;
  generation_error: string | null;
  outline: IArticleOutline | null;
  token_count: number | null;
  generation_time_ms: number | null;
  generated_at: string | null;
  published_at: string | null;
  created_at: string;
  updated_at: string;
}

/**
 * Structured outline generated by the LLM in the first step of generation
 */
export interface IArticleOutline {
  title: string;
  metaDescription: string;
  slug: string;
  sections: Array<{
    heading: string;
    subheadings?: string[];
    keyPoints: string[];
  }>;
}

/**
 * Input for article generation API
 */
export interface IGenerateArticleInput {
  /** The primary keyword or topic for the article */
  keyword: string;
  /** ID of the project this article belongs to */
  projectId: string;
  /** OpenRouter model ID (defaults to config if not specified) */
  model?: string;
  /** Writing tone: professional, casual, witty, academic */
  tone?: 'professional' | 'casual' | 'witty' | 'academic';
  /** Target word count (800-3000, default 1500) */
  targetWordCount?: number;
}

/**
 * Response from article generation API (202 Accepted)
 */
export interface IGenerateArticleResponse {
  articleId: string;
  status: 'generating';
}

/**
 * Response from article details API
 */
export interface IArticleResponse {
  article: IArticle;
}

/**
 * Response from articles listing API
 */
export interface IArticlesListResponse {
  articles: IArticle[];
  total: number;
}

/**
 * Query parameters for articles listing
 */
export interface IArticlesListParams {
  projectId?: string;
  status?: ArticleStatus;
  limit?: number;
  offset?: number;
}
