/**
 * Article Types for AI Content Generation Engine
 *
 * Defines interfaces for articles, generation input/output, and related structures.
 */

/**
 * Article status enum representing the lifecycle of an article
 */
export type ArticleStatus = 'queued' | 'generating' | 'draft' | 'approved' | 'rejected' | 'reviewed' | 'published' | 'failed';

/**
 * Full article interface matching the database schema
 */
export interface IArticle {
  id: string;
  campaign_id: string | null;
  user_id: string;
  project_id: string | null;
  title: string | null;
  content: string | null;
  primary_keyword: string;
  status: ArticleStatus;
  ai_model_used: string | null;
  seo_score: number | null;
  ai_detection_score: number | null;
  word_count: number | null;
  meta_description: string | null;
  published_url: string | null;
  slug: string | null;
  credits_used: number;
  generation_error: string | null;
  rejection_reason: string | null;
  outline: IArticleOutline | null;
  token_count: number | null;
  generation_time_ms: number | null;
  generated_at: string | null;
  published_at: string | null;
  created_at: string;
  updated_at: string;
  // Image generation fields
  image_preset: string | null;
  image_count: number;
}

/**
 * Structured outline generated by the LLM in the first step of generation
 */
export interface IArticleOutline {
  title: string;
  metaDescription: string;
  slug: string;
  sections: Array<{
    heading: string;
    subheadings?: string[];
    keyPoints: string[];
  }>;
}

/**
 * Input for article generation API
 */
export interface IGenerateArticleInput {
  /** The primary keyword or topic for the article */
  keyword: string;
  /** ID of the project this article belongs to */
  projectId: string;
  /** ID of the campaign this article belongs to (REQUIRED) */
  campaignId: string;
  /** OpenRouter model ID (defaults to config if not specified) */
  model?: string;
  /** Writing tone: professional, casual, witty, academic */
  tone?: 'professional' | 'casual' | 'witty' | 'academic';
  /** Target word count (800-3000, default 1500) */
  targetWordCount?: number;
  /** Image generation preset key (optional, no images if not specified) */
  imagePreset?: string;
}

/**
 * Response from article generation API (202 Accepted)
 */
export interface IGenerateArticleResponse {
  articleId: string;
  status: 'generating';
}

/**
 * Response from article details API (with images and campaign)
 */
export interface IArticleDetailResponse {
  article: IArticle & {
    campaigns?: {
      id: string;
      name: string;
    } | null;
    article_images?: Array<{
      id: string;
      position: number;
      image_url: string | null;
      prompt: string;
      status: string;
    }>;
  };
}

/**
 * Response from article details API (legacy)
 */
export interface IArticleResponse {
  article: IArticle;
}

/**
 * Article with campaign info (for list views)
 */
export interface IArticleWithCampaign extends IArticle {
  /** Campaign info (joined) */
  campaigns: {
    id: string;
    name: string;
  } | null;
}

/**
 * Response from articles listing API
 */
export interface IArticlesListResponse {
  articles: IArticleWithCampaign[];
  total: number;
}

/**
 * Query parameters for articles listing
 */
export interface IArticlesListParams {
  projectId?: string;
  status?: ArticleStatus;
  limit?: number;
  offset?: number;
}

/**
 * Article image record from database
 */
export interface IArticleImage {
  id: string;
  article_id: string;
  position: number;
  image_url: string | null;
  prompt: string;
  section_context: string | null;
  replicate_model: string;
  preset_key: string;
  status: 'pending' | 'generating' | 'completed' | 'failed';
  error: string | null;
  replicate_prediction_id: string | null;
  generation_time_ms: number | null;
  created_at: string;
}

/**
 * Image marker parsed from article markdown
 */
export interface IImageMarker {
  position: number;
  sectionContext: string;
}

/**
 * Result from generating a single image
 */
export interface IImageResult {
  position: number;
  imageUrl: string | null;
  prompt: string;
  model: string;
  presetKey: string;
  status: 'completed' | 'failed';
  error?: string;
  generationTimeMs?: number;
  replicatePredictionId?: string;
}
